export const ENABLE_LOGGING = true;

export const PLAYER_SPEED = 80;
export const PLAYER_INVULNERABLE_AFTER_HIT_DURATION = 1000;

export const ENEMY_SPIDER_SPEED = 80;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_MIN = 400;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_MAX = 1500;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_WAIT = 200;

export const ENEMY_WISP_SPEED = 80;
export const ENEMY_WISP_PULSE_SCALE_Y = 1.3;
export const ENEMY_WISP_PULSE_SCALE_X = 1.3;
export const ENEMY_WISP_PULSE_DURATION = 500;
