export const ENABLE_LOGGING = false;

export const PLAYER_SPEED = 80;
export const PLAYER_INVULNERABLE_AFTER_HIT_DURATION = 1000;
export const PLAYER_HURT_PUSH_BACK_SPEED = 50;
export const PLAYER_START_MAX_HEALTH = 6;

export const ENEMY_SPIDER_SPEED = 80;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_MIN = 400;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_MAX = 1500;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_WAIT = 200;
export const ENEMY_SPIDER_HURT_PUSH_BACK_SPEED = 50;
export const ENEMY_SPIDER_START_MAX_HEALTH = 6;


export const ENEMY_WISP_SPEED = 80;
export const ENEMY_WISP_PULSE_SCALE_Y = 1.3;
export const ENEMY_WISP_PULSE_SCALE_X = 1.3;
export const ENEMY_WISP_PULSE_DURATION = 500;
export const ENEMY_WISP_START_MAX_HEALTH = 1;

export const HURT_PUSH_BACK_DELAY = 200;

export const THROW_ITEM_SPEED = 300;
export const THROW_ITEM_DELAY_BEFORE_CALLBACK = 200;

export const LIFT_ITEM_ANIMATION_ENABLE_DEBUGGING = true;
export const LIFT_ITEM_ANIMATION_DELAY = 0;
export const LIFT_ITEM_ANIMATION_DURATION = 250;